Feature - Reimplement migrations mechanism
rock-symphony/propel-orm-plugin pull request #3
Opened 2021-09-08 09:47 UTC by marko-ogg

2021-09-08 12:06 UTC, pestaa commented
Nice work! :racehorse: 

One note: I wouldn't change the default table name, because users of this project will have to rename their own tables using a migration, which is, you know, _dangerops_.

2021-09-13 10:41 UTC, e1himself requested changes
@marko-ogg Please reformat these changes to comply with the rest of repository code style (2 spaces indents). Otherwise it's impossible to follow the diffs.

Changing/fixing code style should be a different exercise done in a separate PR.

2021-09-15 15:07 UTC, marko-ogg commented
@pestaa @e1himself this is ready to be reviewed tested.

In the new mechanism, I've introduced "migration database".

While working on this, I encountered some tricky, not reliable cases when migration table is maintained across all databases.

For example, let's say that we maintain separate migration table in every database that is specified in `databases.yml`. Which migrations we consider as "executed" for particular database:
- The ones that are executed in that database? What if particular migration does not execute any statements under that particular database?
- The ones that are executed for all databases that are specified in the migration? In this case, migration table in every database is just a copy of migration tables from other databases. This complicates maintenance a lot.

Also, what if someone in future, adds new database in some old migration's `getUpSQL`. Should we detect that and execute these statements for the specified database? I don't think so, once the migration is marked as executed, no editing should trigger it to execute again.

I think the easiest and most simple solution is to specify which database is responsible for keeping track of executed migrations, and have the definition of executed migration as follows: `migration that is executed in all databases that are specified in migration's getUpSQL method`.

Btw, I'm not very satisfied with the code architecture here, but I think we should keep it to as least changes as possible.

2022-01-18 14:50 UTC, e1himself commented
After thinking about these changes for a while, I've came to a conclusion that this is not the right thing to do.

There are enough problems with this PR to not consider it as a good contribution to the (stale) project of propel-orm-plugin. Plus, I don't want this to diverge far from the original codebase, as it will be then harder to migrate our app to Propel2.

Instead, I believe it's better to move this changes to the application land. See https://github.com/prezly/prezly/pull/10588

2022-01-18 14:50 UTC, closed without merging